name: 学校信息错误
description: 学校名称、地区错误等情况。
labels: ["学校信息错误"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢您的反馈！如果情况允许，您也可以直接发起 Pull Request 进行更正。

        欢迎您在 [项目主页](https://github.com/OIerDb-ng/OIerDb) 的右上方为我们点亮 Star，感谢支持！

  - type: input
    id: contact
    attributes:
      label: 学校名称
      placeholder: ex. 石家庄市第二中学
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 错误类别
      description: 这个学校的信息出现了什么问题？
      options:
        - 名称有误
        - 地区有误
        - 错误合并
        - 错误拆分
        - 其他
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 错误详情
      description: 请具体描述这个学校的信息出现了什么错误，并附上该学校的 ID（或指向该学校详情页的链接）。如果涉及到更名等情况，请提供可靠的、能够公开查询的证明材料（如百度百科页面、官网公告等）。
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 承诺
      options:
        - label: 在提交这个 issue 前，我已确认我提交的信息是真实有效的。
          required: true
